"""modify bookings

Revision ID: b88f8f54b219
Revises: 5f256349f824
Create Date: 2022-05-19 14:58:43.756918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88f8f54b219'
down_revision = '5f256349f824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_name_key', 'bookings', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bookings_name_key', 'bookings', ['name'])
    # ### end Alembic commands ###
